import { Vendor, Product, Order, Review, Staff, Payout } from '../types';

export const initialVendors: Vendor[] = [
  {
    id: 'v1',
    storeName: 'TechHut',
    email: 'techhut@example.com',
    phone: '03001234567',
    description: 'Best electronics in Karachi',
    timings: { open: '09:00', close: '22:00' },
    isOpen: true,
    minOrderAmount: 1000,
    deliveryRadius: 15,
    taxConfig: 16,
    deliveryCharges: { base: 100, perKm: 20 },
    freeDeliveryThreshold: 5000,
  },
  {
    id: 'v2',
    storeName: 'FreshMart',
    email: 'freshmart@example.com',
    phone: '03009876543',
    description: 'Fresh groceries delivered to your door',
    timings: { open: '08:00', close: '23:00' },
    isOpen: true,
    minOrderAmount: 500,
    deliveryRadius: 10,
    taxConfig: 0,
    deliveryCharges: { base: 50, perKm: 10 },
    freeDeliveryThreshold: 2000,
  },
  {
    id: 'v3',
    storeName: 'BurgerHouse',
    email: 'burgerhouse@example.com',
    phone: '03001112233',
    description: 'Juicy burgers and crispy fries',
    timings: { open: '11:00', close: '02:00' },
    isOpen: true,
    minOrderAmount: 300,
    deliveryRadius: 5,
    taxConfig: 16,
    deliveryCharges: { base: 50, perKm: 15 },
    freeDeliveryThreshold: 1500,
  },
  {
    id: 'v4',
    storeName: 'SweetBakery',
    email: 'sweetbakery@example.com',
    phone: '03004445566',
    description: 'Freshly baked cakes and pastries',
    timings: { open: '07:00', close: '21:00' },
    isOpen: true,
    minOrderAmount: 200,
    deliveryRadius: 8,
    taxConfig: 16,
    deliveryCharges: { base: 60, perKm: 12 },
    freeDeliveryThreshold: 1000,
  },
];

export const initialProducts: Product[] = [
  {
    id: 'p1',
    vendorId: 'v1',
    name: 'Smartphone X',
    description: 'Latest model with 128GB storage',
    price: 50000,
    images: ['https://picsum.photos/seed/phone/400/300'],
    category: 'Smartphones',
    stockQuantity: 50,
    isAvailable: true,
  },
  {
    id: 'p2',
    vendorId: 'v1',
    name: 'Laptop Pro',
    description: 'High performance laptop for professionals',
    price: 150000,
    images: ['https://picsum.photos/seed/laptop/400/300'],
    category: 'Laptops',
    stockQuantity: 20,
    isAvailable: true,
  },
  {
    id: 'p3',
    vendorId: 'v2',
    name: 'Apples (1kg)',
    description: 'Fresh red apples',
    price: 300,
    images: ['https://picsum.photos/seed/apple/400/300'],
    category: 'Fruits',
    stockQuantity: 100,
    isAvailable: true,
  },
  {
    id: 'p4',
    vendorId: 'v3',
    name: 'Zinger Burger',
    description: 'Crispy chicken burger with fries',
    price: 450,
    images: ['https://picsum.photos/seed/burger/400/300'],
    category: 'Burgers',
    stockQuantity: 500,
    isAvailable: true,
  },
  {
    id: 'p5',
    vendorId: 'v4',
    name: 'Chocolate Cake',
    description: 'Rich chocolate cake (2lbs)',
    price: 1200,
    images: ['https://picsum.photos/seed/cake/400/300'],
    category: 'Cakes',
    stockQuantity: 15,
    isAvailable: true,
  },
];

export const initialOrders: Order[] = [
  {
    id: 'o1',
    vendorId: 'v3',
    customerName: 'Ali Khan',
    customerPhone: '03001231234',
    customerAddress: 'House 1, Street 2, F-8, Islamabad',
    items: [{ productId: 'p4', name: 'Zinger Burger', quantity: 2, price: 450 }],
    totalAmount: 900,
    status: 'Pending',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'o2',
    vendorId: 'v1',
    customerName: 'Sara Ahmed',
    customerPhone: '03009879876',
    customerAddress: 'Apt 5, Block A, Clifton, Karachi',
    items: [{ productId: 'p1', name: 'Smartphone X', quantity: 1, price: 50000 }],
    totalAmount: 50000,
    status: 'Delivered',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const initialReviews: Review[] = [
  {
    id: 'r1',
    vendorId: 'v3',
    orderId: 'o1',
    customerName: 'Ali Khan',
    rating: 5,
    comment: 'Best burger in town!',
    createdAt: new Date().toISOString(),
  },
];

export const initialStaff: Staff[] = [
  {
    id: 's1',
    vendorId: 'v3',
    name: 'Raza Ali',
    phone: '03005556666',
    cnic: '37405-1234567-1',
    status: 'Active',
  },
];

export const initialPayouts: Payout[] = [
  {
    id: 'po1',
    vendorId: 'v3',
    amount: 5000,
    status: 'Completed',
    date: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
];
